###
#User related APIs

POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
    "username": "rashi",
    "password": "rashi22",
    "email": "rashi22@gmail.com",
    "name": "Rashi"
}

###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
    "email": "rashi22@gmail.com",
    "password": "rashi22"
}

###

GET http://localhost:9090/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token":"ed7559c50747c11412b62c46341c1115dde6764ea7e213fcc04dd9ed5dacf338"
}

###

POST http://localhost:9090/update_profile_data HTTP/1.1
Content-Type: application/json

{
    "token":"696fe95430854550e12b887adc8d333809c63b4810f3fbd152154eb16976d509",
    "bio": "",
    "currenPost": "CFO",
    "pastWork": [
        {
            "company":"Google",
            "position":"CFO",
            "years":"4+"
        }
    ],
    "education": [
        {
            "school":"IIT",
            "degree":"B.Tech",
            "fieldOfStudy":"2016-2020"
        }
    ]
}

###
# API for upload_profile_picture
# curl --location 'http://localhost:9090/upload_profile_picture' \
# --form 'token="51628b573c9ccac85e0c24a286618d7ee63ed766dd66f6737481b677986d77c7"' \
# --form 'profile_picture=@"/Users/divyagupta/Desktop/zerodha-clone/zerodha/frontend/public/media/images/pricing0.svg"'


GET http://localhost:9090/user/get_all_user_profile HTTP/1.1
Content-Type: application/json

###
# Profile related APIs

#Create Post API
#curl --location 'http://localhost:9090/post' \
# --form 'token="1606257ae381c5265c6b45eec97cccc3f26baa07a091fa8051793e3cab491132"' \
# --form 'body="I'\''m trying to create a Full Stack AI application"' \
# --form 'media=@"/Users/divyagupta/Desktop/zerodha-clone/zerodha/frontend/public/media/images/streakLogo.png"'

###

GET http://localhost:9090/posts HTTP/1.1
Content-Type: application/json

# "body": "I'm trying to create a Full Stack AI application",
# "likes": 0,
# 
# "active": true, //admin has the right to make it false if detected as NFSW by AI
# 
# for heavy jobs where you have to check the security for every post, corn jobs are used on the backend

